version: '3.8'

services:
  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BOT_TOKEN=6853220461:AAGIJo2a3GIMMqgz1w9iISW3Lv7ZnvAoRa8
      - CHAT_ID=-1002060021902
      - COROUTINE_DEBUG=True
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - OPENAI_URL=http://local-ai:8080/v1
      - OPENAI_TOKEN=lm-studio
      - LLM_MODEL=gpt-4
    ports:
      - "8000:8000"
    networks:
      - bot_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_network

volumes:
  pgdata:

networks:
  bot_network:
    external: true
